// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdVzL2_7Y31yw9j8NTXVCCtQVA9ZHmrqk',
    appId: '1:534110908892:web:5762058386a11d44fb9f19',
    messagingSenderId: '534110908892',
    projectId: 'mindnoteapp-e5af4',
    authDomain: 'mindnoteapp-e5af4.firebaseapp.com',
    storageBucket: 'mindnoteapp-e5af4.appspot.com',
    measurementId: 'G-NHK7H6GD41',
    databaseURL: "https://mindnoteapp-e5af4-default-rtdb.asia-southeast1.firebasedatabase.app",      //add new IMPORTATNT

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7gSlrqtnvhvB9Ces9T8d0vp-ROZLBAc',
    appId: '1:534110908892:android:e297b87977cc7961fb9f19',
    messagingSenderId: '534110908892',
    projectId: 'mindnoteapp-e5af4',
    storageBucket: 'mindnoteapp-e5af4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZNsCT2uS25USDyV0GxZvNTdd9PNS4V0',
    appId: '1:534110908892:ios:23b8b244502799a0fb9f19',
    messagingSenderId: '534110908892',
    projectId: 'mindnoteapp-e5af4',
    storageBucket: 'mindnoteapp-e5af4.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZNsCT2uS25USDyV0GxZvNTdd9PNS4V0',
    appId: '1:534110908892:ios:23b8b244502799a0fb9f19',
    messagingSenderId: '534110908892',
    projectId: 'mindnoteapp-e5af4',
    storageBucket: 'mindnoteapp-e5af4.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdVzL2_7Y31yw9j8NTXVCCtQVA9ZHmrqk',
    appId: '1:534110908892:web:fa550faf54cebca3fb9f19',
    messagingSenderId: '534110908892',
    projectId: 'mindnoteapp-e5af4',
    authDomain: 'mindnoteapp-e5af4.firebaseapp.com',
    storageBucket: 'mindnoteapp-e5af4.appspot.com',
    measurementId: 'G-4DZ3SZ9DXL',
  );
}
